import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box } from "@chakra-ui/react";
import HomeScOne from "@/component/HomeScOne";
import HomeScTwo from "@/component/HomeScTwo";
import HomeScThree from "@/component/HomeScThree";
import HomeScFive from "@/component/HomeScFive";
import HomeScSix from "@/component/HomeScSix";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rummy Mate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '944704077206139');
              fbq('track', 'PageView');
            `
          }}
        />
      </Head>
      <Box className="">
        <HomeScOne />
        <HomeScTwo />
        <HomeScThree />
        <HomeScFive />
        <HomeScSix />
      </Box>
    </>
  );
}
