import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box } from "@chakra-ui/react";
import HomeScOne from "@/component/HomeScOne";
import HomeScTwo from "@/component/HomeScTwo";
import HomeScThree from "@/component/HomeScThree";
import HomeScFive from "@/component/HomeScFive";
import HomeScSix from "@/component/HomeScSix";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rummy Mate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="">
        <HomeScOne />
        <HomeScTwo />
        <HomeScThree />
        <HomeScFive />
        <HomeScSix />
      </Box>
    </>
  );
}
